module.exports = {
  prefix: '!',
  admins: ['100060812419294', '100089655356822', '61554894353095', '100053875564339'],
  logRecipientId: '',
  casinoName: 'Bot',
  currencyEmoji: '💰',
  messenger: {
    port: 3000,
    webhookPath: '/webhook',
    graphVersion: 'v24.0',
    pageId: '',
    botAvatarUrl: ''
  },
  embed: {
    primary: 0xD4AF37
  },
  antiSpam: {
    maxCommands: 6,
    perSeconds: 10,
    muteSeconds: 15
  },
  cooldowns: {
    default: 3,
    help: 3,
    bal: 2,
    daily: 5,
    work: 600,
    crime: 900,
    rob: 20,
    slots: 4,
    blackjack: 10,
    coinflip: 4,
    ruletka: 5,
    bet: 3,
    duel: 3,
    leaderboard: 8,
    wplac: 3,
    wyplac: 3,
    sklep: 3,
    eq: 3,
    marry: 12,
    pfp: 4,
    admadd: 2,
    del: 2,
    weather: 5,
    wiki: 5,
    dictionary: 5,
    news: 8,
    joke: 3,
    fact: 3,
    quote: 3,
    xkcd: 5,
    movie: 6,
    currency: 5,
    hello: 2,
    bye: 2,
    thanks: 2,
    loteria: 3,
    loteriastart: 2,
    podatki: 3
  },
  economy: {
    defaultUser: {
      balance: 5000,
      bank: 10000,
      level: 5,
      xp: 240,
      totalWon: 12000,
      totalLost: 8000,
      gamesPlayed: 53,
      wins: 0,
      losses: 0,
      commandsUsed: 0,
      lastActiveThreadId: null,
      prestige: 1,
      bio: '',
      badges: [],
      marriedTo: null,
      dailyCooldown: 0,
      messageCount: 0,
      groupMessages: {}
    },
    maxBet: 100000,
    dailyMin: 900,
    dailyMax: 2200,
    dailyVipBonus: 1.25,
    workMin: 5000,
    workMax: 25000,
    workVipBonus: 1.1,
    crimeSuccessChance: 0.52,
    crimeWinMin: 400,
    crimeWinMax: 2400,
    crimeLoseMin: 200,
    crimeLoseMax: 1100,
    robSuccessChance: 0.38,
    robMinTarget: 2500,
    robMinPercent: 0.1,
    robMaxPercent: 0.3,
    bankBaseCapacity: 100000,
    bankVipBonus: 25000,
    bankPrestigeBonus: 25000,
    goldenCardBonus: 50000,
    xpPerLevelBase: 180,
    xpPerLevelGrowth: 55
  },
  shopItems: {
    klodka: {
      name: 'Klodka',
      emoji: '🔒',
      price: 35000,
      description: 'Chroni przed kradzieza przez innego gracza (!rob). Zuzywana przy probie robu.',
      type: 'stackable'
    },
    piwo: {
      name: 'Piwo',
      emoji: '🍺',
      price: 50000,
      description: 'Uzyj przed !rob: 50% szans na +5% wiekszy lup (25% zamiast 20%), ale przy wpadce tracisz 40% zamiast 30%.',
      type: 'stackable'
    },
    ticket: {
      name: 'Bilet Loterii',
      emoji: '🎟️',
      price: 50000,
      description: 'Bilet na loterię (losowanie co 10 min, max 5 szt.).',
      type: 'stackable'
    },
    bomba: {
      name: 'Bomba',
      emoji: '💣',
      price: 100000,
      description: 'Pułapka na złodzieja: kradnie 40% jego portfela i nakłada na niego 30 minut cooldownu.',
      type: 'stackable'
    },
    paczka_brazowa: {
      name: 'Brązowa Paczka',
      emoji: '🟫',
      price: 50000,
      description: 'Otwórz: !otworz brazowa | Wygrana: 25 000–75 000 + 10% szans na Bilet Loterii.',
      type: 'stackable'
    },
    paczka_srebrna: {
      name: 'Srebrna Paczka',
      emoji: '⬜',
      price: 100000,
      description: 'Otwórz: !otworz srebrna | Wygrana: 75 000–150 000 + 10% szans na Kłódkę lub Piwo.',
      type: 'stackable'
    },
    paczka_zlota: {
      name: 'Złota Paczka',
      emoji: '🟨',
      price: 200000,
      description: 'Otwórz: !otworz zlota | Wygrana: 150 000–250 000 + 10% szans na Bombę lub Kłódkę+Piwo.',
      type: 'stackable'
    },
    paczka_diamentowa: {
      name: 'Diamentowa Paczka',
      emoji: '🟦',
      price: 500000,
      description: 'Otwórz: !otworz diamentowa | Wygrana: 250 000–750 000 + 10% szans na VIP Pass lub Ulepszenie Banku!',
      type: 'stackable'
    },
    // Poniższe itemy są niedostępne w sklepie — wypadają tylko z paczek
    vip: {
      name: 'VIP Pass',
      emoji: '👑',
      price: 100000,
      description: 'Daje bonus do !daily i !work oraz zwiększa pojemność banku.',
      type: 'permanent',
      buyable: false,
      shopNote: 'Dostępny tylko z 🟦 Diamentowej Paczki!'
    },
    sejf: {
      name: 'Ulepszenie Banku',
      emoji: '🏦',
      price: 150000,
      description: 'Zwiększa pojemność banku o 75 000.',
      type: 'permanent',
      buyable: false,
      shopNote: 'Dostępne tylko z 🟦 Diamentowej Paczki!'
    }
  },
  badges: {
    vip: '👑 VIP',
    bogacz: '🪙 Bogacz',
    milioner: '💸 Milioner',
    miliarder: '💎 Miliarder',
    gracz: '🔨 Gracz',
    weteran: '⚡ Weteran',
    uzalezniony: '🌀 Uzależniony',
    hazardzista: '🎲 Hazardzista',
    rekin: '🎰 Rekin Kasyna',
    bog: '🃏 Bóg Kasyna',
    married: '💍 Małżeństwo',
    gadatliwy: '💬 Gadatliwy',
    spamer: '🗣️ Spamer',
    krolSpamu: '📢 Król Spamu',
    klikacz: '⌨️ Klikacz',
    wladcaBota: '🤖 Władca Bota',
    nowicjusz: '📈 Nowicjusz',
    ekspert: '🔥 Ekspert',
    mistrz: '👑 Mistrz',
    zwyciezca: '🏆 Zwycięzca',
    boss: '👑 Boss Gangu',
    zastepca: '⭐ Zastępca',
    czlonek: '👤 Członek Gangu'
  }
};
