module.exports = {
  prefix: '!',
  admins: ['100060812419294', '100089655356822', '61554894353095', '100053875564339'],
  logRecipientId: '',
  casinoName: 'Bot',
  currencyEmoji: '💰',
  messenger: {
    port: 3000,
    webhookPath: '/webhook',
    graphVersion: 'v24.0',
    pageId: '',
    botAvatarUrl: ''
  },
  embed: {
    primary: 0xD4AF37
  },
  antiSpam: {
    maxCommands: 6,
    perSeconds: 10,
    muteSeconds: 15,
    cooldownBlacklist: {
      maxNotifications: 5,
      perSeconds: 30
    }
  },
  cooldowns: {
    default: 3,
    help: 3,
    bal: 2,
    daily: 5,
    work: 600,
    crime: 900,
    rob: 20,
    slots: 4,
    blackjack: 10,
    coinflip: 4,
    ruletka: 5,
    bet: 3,
    duel: 3,
    leaderboard: 8,
    wplac: 3,
    wyplac: 3,
    sklep: 3,
    eq: 3,
    marry: 12,
    pfp: 4,
    admadd: 2,
    del: 2,
    weather: 5,
    wiki: 5,
    dictionary: 5,
    news: 8,
    joke: 3,
    fact: 3,
    quote: 3,
    xkcd: 5,
    movie: 6,
    currency: 5,
    hello: 2,
    bye: 2,
    thanks: 2,
    loteria: 3,
    loteriastart: 2,
    podatki: 3,
    artefakty: 3,
    rynek: 3,
    itemadd: 2
  },
  economy: {
    defaultUser: {
      balance: 5000,
      bank: 10000,
      level: 5,
      xp: 240,
      totalWon: 12000,
      totalLost: 8000,
      gamesPlayed: 53,
      wins: 0,
      losses: 0,
      commandsUsed: 0,
      lastActiveThreadId: null,
      prestige: 1,
      bio: '',
      badges: [],
      marriedTo: null,
      dailyCooldown: 0,
      messageCount: 0,
      groupMessages: {}
    },
    maxBet: 100000,
    dailyMin: 900,
    dailyMax: 2200,
    dailyVipBonus: 1.25,
    workMin: 5000,
    workMax: 25000,
    workVipBonus: 1.1,
    crimeSuccessChance: 0.52,
    crimeWinMin: 400,
    crimeWinMax: 2400,
    crimeLoseMin: 200,
    crimeLoseMax: 1100,
    robSuccessChance: 0.38,
    robMinTarget: 2500,
    robMinPercent: 0.1,
    robMaxPercent: 0.3,
    bankBaseCapacity: 100000,
    bankVipBonus: 25000,
    bankPrestigeBonus: 25000,
    goldenCardBonus: 50000,
    xpPerLevelBase: 180,
    xpPerLevelGrowth: 55
  },
  shopItems: {
    klodka: {
      name: 'Klodka',
      emoji: '🔒',
      price: 35000,
      shortDesc: 'Chroni przed kradzieżą (!rob).',
      description: 'Chroni przed kradzieżą przez innego gracza (!rob). Kłódka jest zużywana przy każdej próbie robu — złodziej traci możliwość kradzieży i odchodzi z niczym.',
      type: 'stackable'
    },
    piwo: {
      name: 'Piwo',
      emoji: '🍺',
      price: 50000,
      shortDesc: 'Bonus do !rob (+5% łup lub -10% kara).',
      description: 'Użyj przed !rob: daje 50% szans na zwiększony łup (+5%, czyli 25% zamiast 20%). Uwaga — przy wpadce kara rośnie do 40% zamiast 30%. Ryzyko się opłaca odważnym!',
      type: 'stackable'
    },
    ticket: {
      name: 'Bilet Loterii',
      emoji: '🎟️',
      price: 50000,
      shortDesc: 'Udział w loterii co 10 min (max 5 szt.).',
      description: 'Bilet uprawnia do udziału w automatycznej loterii, która losuje zwycięzcę co 10 minut. Im więcej biletów, tym większa szansa wygranej. Nagroda = liczba biletów × 50 000. Limit: 5 biletów na osobę.',
      type: 'stackable'
    },
    bomba: {
      name: 'Bomba',
      emoji: '💣',
      price: 100000,
      shortDesc: 'Pułapka: obrabowuje złodzieja przy !rob.',
      description: 'Aktywna pułapka na złodzieja. Gdy ktoś spróbuje cię okraść (!rob), bomba wybucha — kradnie 40% portfela złodzieja i nakłada na niego 30 minut cooldownu na !rob. Bomba zużywa się po aktywacji.',
      type: 'stackable'
    },
    paczka_brazowa: {
      name: 'Brązowa Paczka',
      emoji: '🟫',
      price: 50000,
      shortDesc: 'Lootbox: 22.5k–72.5k + 10% szans na Bilet.',
      description: 'Otwórz komendą: !otworz brazowa\nZawartość: losowa kwota od 22 500 do 72 500 viccoinów (rozkład równomierny).\nBonus drop (10%): 🎟️ Bilet Loterii.',
      type: 'stackable'
    },
    paczka_srebrna: {
      name: 'Srebrna Paczka',
      emoji: '⬜',
      price: 100000,
      shortDesc: 'Lootbox: 71.25k–146.25k + 10% szans na przedmiot.',
      description: 'Otwórz komendą: !otworz srebrna\nZawartość: losowa kwota od 71 250 do 146 250 viccoinów.\nBonus drop (10%): 5% szans na 🔒 Kłódkę, 5% szans na 🍺 Piwo.',
      type: 'stackable'
    },
    paczka_zlota: {
      name: 'Złota Paczka',
      emoji: '🟨',
      price: 200000,
      shortDesc: 'Lootbox: 145k–245k + 10% szans na przedmiot.',
      description: 'Otwórz komendą: !otworz zlota\nZawartość: losowa kwota od 145 000 do 245 000 viccoinów.\nBonus drop (10%): 5% na 💣 Bombę, 3% na 🔒 Kłódkę + 🍺 Piwo jednocześnie, 2% na 🎟️ Bilet.',
      type: 'stackable'
    },
    paczka_diamentowa: {
      name: 'Diamentowa Paczka',
      emoji: '🟦',
      price: 500000,
      shortDesc: 'Lootbox: 225k–725k + 10% szans na VIP/Sejf!',
      description: 'Otwórz komendą: !otworz diamentowa\nZawartość: losowa kwota od 225 000 do 725 000 viccoinów.\nBonus drop (10%): 5% na 👑 VIP Pass, 5% na 🏦 Ulepszenie Banku.\nJeśli już posiadasz dany przedmiot — otrzymujesz zamiennik o podobnej wartości.',
      type: 'stackable'
    },
    // Poniższe itemy są niedostępne w sklepie — wypadają tylko z paczek
    vip: {
      name: 'VIP Pass',
      emoji: '👑',
      price: 100000,
      shortDesc: 'Bonus do !daily, !work i większy bank.',
      description: 'Daje stały bonus do nagród z !daily (+25%) i !work (+10%) oraz zwiększa pojemność banku o 25 000. Tylko jeden egzemplarz na gracza. Dostępny wyłącznie z 🟦 Diamentowej Paczki.',
      type: 'permanent',
      buyable: false,
      shopNote: 'Dostępny tylko z 🟦 Diamentowej Paczki!'
    },
    sejf: {
      name: 'Ulepszenie Banku',
      emoji: '🏦',
      price: 150000,
      shortDesc: 'Zwiększa pojemność banku o 75 000.',
      description: 'Jednorazowy upgrade: trwale zwiększa pojemność banku o 75 000 viccoinów. Tylko jeden egzemplarz na gracza. Dostępny wyłącznie z 🟦 Diamentowej Paczki.',
      type: 'permanent',
      buyable: false,
      shopNote: 'Dostępne tylko z 🟦 Diamentowej Paczki!'
    },
    krwawy_zeton: {
      name: 'Krwawy Żeton',
      emoji: '🩸',
      price: 0,
      shortDesc: 'Pasywny PvP: +6% szansa rob, +4% łup, +8% kara przy wpadce.',
      description: 'Zwiększa szansę powodzenia komendy !rob o 6%. Jeśli kradzież się uda, otrzymujesz +4% dodatkowego łupu. Jeśli nie, kara jest zwiększona o 8%. Efekty się nie stackują.',
      type: 'stackable',
      buyable: false,
      shopNote: 'Dostępny z wojen gangów (4%) lub paczki diamentowej (2%).'
    },
    przekupiony_krupier: {
      name: 'Przekupiony Krupier',
      emoji: '🧠',
      price: 0,
      shortDesc: 'Hazard passive: 3% większa szansa na korzystną kartę w blackjacku.',
      description: 'Daje 3% szansy na dobór korzystniejszej karty w grze !blackjack podczas dobierania (hit). Efekty się nie stackują.',
      type: 'stackable',
      buyable: false,
      shopNote: 'Dostępny tylko z 🩶 Tytanowej Paczki (2%).'
    },
    zlota_karta: {
      name: 'Złota Karta',
      emoji: '💳',
      price: 0,
      shortDesc: '+50k miejsca w banku.',
      description: 'Zwiększa pojemność Twojego banku o 50 000 viccoinów. Efekty się nie stackują.',
      type: 'stackable',
      buyable: false,
      shopNote: 'Dostępna tylko ze Złotej Paczki (2%).'
    },
    stary_zegar: {
      name: 'Stary Zegar',
      emoji: '⏰',
      price: 0,
      shortDesc: '10% krótszy cooldown na !work oraz !crime.',
      description: 'Skraca cooldown na komendy !work oraz !crime o 10%. Efekty się nie stackują.',
      type: 'stackable',
      buyable: false,
      shopNote: 'Dostępny tylko z Diamentowej Paczki (0.5%).'
    },
    kamera: {
      name: 'Kamera',
      emoji: '📷',
      price: 0,
      shortDesc: 'Defensywny: +5% więcej z kary gdy złodziej wpadnie.',
      description: 'Gdy ktoś próbuje Cię okraść i zostanie przyłapany, dostajesz dodatkowo 5% z kwoty kary nałożonej na złodzieja. Efekty się nie stackują.',
      type: 'stackable',
      buyable: false,
      shopNote: 'Dostępna tylko ze Złotej Paczki (1%).'
    },
    paczka_tytanowa: {
      name: 'Tytanowa Paczka',
      emoji: '🩶',
      price: 800000,
      shortDesc: 'Lootbox: 550k–1M + 2% na Krupiera, 40% na bombę/piwo/kłódkę.',
      description: 'Otwórz komendą: !otworz tytanowa\nZawartość: losowa kwota od 550 000 do 1 000 000 viccoinów.\nBonus drop (2%): 🧠 Przekupiony Krupier.\nDodatkowo 40% szans na wylosowanie bomby, piwa lub kłódki.',
      type: 'stackable',
      buyable: true
    }
  },
  badges: {
    vip: '👑 VIP',
    bogacz: '🪙 Bogacz',
    milioner: '💸 Milioner',
    miliarder: '💎 Miliarder',
    gracz: '🔨 Gracz',
    weteran: '⚡ Weteran',
    uzalezniony: '🌀 Uzależniony',
    hazardzista: '🎲 Hazardzista',
    rekin: '🎰 Rekin Kasyna',
    bog: '🃏 Bóg Kasyna',
    married: '💍 Małżeństwo',
    gadatliwy: '💬 Gadatliwy',
    spamer: '🗣️ Spamer',
    krolSpamu: '📢 Król Spamu',
    klikacz: '⌨️ Klikacz',
    wladcaBota: '🤖 Władca Bota',
    nowicjusz: '📈 Nowicjusz',
    ekspert: '🔥 Ekspert',
    mistrz: '👑 Mistrz',
    zwyciezca: '🏆 Zwycięzca',
    boss: '👑 Boss Gangu',
    zastepca: '⭐ Zastępca',
    czlonek: '👤 Członek Gangu'
  }
};
