const PLAYERS_DB = {
  'Bayern Monachium': ['Harry Kane', 'Jamal Musiala', 'Leroy Sane', 'Joshua Kimmich', 'Manuel Neuer', 'Thomas Müller', 'Alphonso Davies', 'Kingsley Coman'],
  'Real Madryt': ['Jude Bellingham', 'Vinicius Junior', 'Kylian Mbappe', 'Luka Modric', 'Federico Valverde', 'Rodrygo', 'Aurelien Tchouameni', 'Antonio Rüdiger'],
  'Paris Saint-Germain': ['Ousmane Dembele', 'Warren Zaire-Emery', 'Vitinha', 'Achraf Hakimi', 'Marquinhos', 'Bradley Barcola', 'Gianluigi Donnarumma', 'Milan Skriniar'],
  'Liverpool FC': ['Mohamed Salah', 'Virgil van Dijk', 'Alexis Mac Allister', 'Luis Diaz', 'Trent Alexander-Arnold', 'Alisson Becker', 'Darwin Nunez', 'Dominik Szoboszlai'],
  'Inter Mediolan': ['Lautaro Martinez', 'Marcus Thuram', 'Nicolo Barella', 'Hakan Calhanoglu', 'Federico Dimarco', 'Alessandro Bastoni', 'Benjamin Pavard', 'Yann Sommer'],
  'Manchester City': ['Erling Haaland', 'Kevin De Bruyne', 'Rodri', 'Phil Foden', 'Bernardo Silva', 'Ruben Dias', 'Ederson', 'Kyle Walker'],
  'Arsenal FC': ['Bukayo Saka', 'Martin Ødegaard', 'Declan Rice', 'William Saliba', 'Kai Havertz', 'Gabriel Martinelli', 'Gabriel Magalhaes', 'Ben White'],
  'FC Barcelona': ['Robert Lewandowski', 'Lamine Yamal', 'Pedri', 'Gavi', 'Frenkie de Jong', 'Raphinha', 'Ronald Araujo', 'Marc-Andre ter Stegen'],
  'Bayer Leverkusen': ['Florian Wirtz', 'Granit Xhaka', 'Alex Grimaldo', 'Jeremie Frimpong', 'Victor Boniface', 'Patrik Schick', 'Jonathan Tah', 'Robert Andrich'],
  'Atletico Madryt': ['Antoine Griezmann', 'Julian Alvarez', 'Conor Gallagher', 'Rodrigo De Paul', 'Jan Oblak', 'Koke', 'Marcos Llorente', 'Jose Maria Gimenez'],
  'Borussia Dortmund': ['Gregor Kobel', 'Julian Brandt', 'Emre Can', 'Marcel Sabitzer', 'Nico Schlotterbeck', 'Karim Adeyemi', 'Serhou Guirassy', 'Jamie Gittens'],
  'Chelsea FC': ['Cole Palmer', 'Enzo Fernandez', 'Nicolas Jackson', 'Moises Caicedo', 'Christopher Nkunku', 'Reece James', 'Levi Colwill', 'Marc Cucurella'],
  'AS Roma': ['Paulo Dybala', 'Lorenzo Pellegrini', 'Gianluca Mancini', 'Bryan Cristante', 'Stephan El Shaarawy', 'Artem Dovbyk', 'Leandro Paredes', 'Evan N\'Dicka'],
  'SL Benfica': ['Angel Di Maria', 'Nicolas Otamendi', 'Orkun Kökcü', 'Florentino Luis', 'Arthur Cabral', 'Alexander Bah', 'Anatoliy Trubin'],
  'Sporting CP': ['Viktor Gyökeres', 'Pedro Goncalves', 'Morten Hjulmand', 'Marcus Edwards', 'Trincao', 'Goncalo Inacio', 'Ousmane Diomande'],
  'Atalanta Bergamo': ['Gianluca Scamacca', 'Ademola Lookman', 'Ederson', 'Giorgio Scalvini', 'Charles De Ketelaere', 'Mario Pasalic', 'Davide Zappacosta'],
  'Aston Villa': ['Ollie Watkins', 'Emiliano Martinez', 'Leon Bailey', 'John McGinn', 'Ezri Konsa', 'Morgan Rogers', 'Lucas Digne', 'Boubacar Kamara'],
  'Eintracht Frankfurt': ['Omar Marmoush', 'Mario Götze', 'Kevin Trapp', 'Hugo Larsson', 'Robin Koch', 'Ansgar Knauff', 'Ellyes Skhiri', 'Willian Pacho'],
  'Tottenham Hotspur': ['Son Heung-min', 'James Maddison', 'Cristian Romero', 'Dejan Kulusevski', 'Guglielmo Vicario', 'Brennan Johnson', 'Dominic Solanke', 'Pedro Porro'],
  'FC Porto': ['Diogo Costa', 'Galeno', 'Alan Varela', 'Nico Gonzalez', 'Ivan Jaime', 'Stephen Eustaquio', 'Otavio', 'Pepê'],
  'Manchester United': ['Bruno Fernandes', 'Marcus Rashford', 'Casemiro', 'Alejandro Garnacho', 'Rasmus Højlund', 'Kobbie Mainoo', 'Matthijs de Ligt', 'Lisandro Martinez'],
  'Fiorentina': ['Cristiano Biraghi', 'Lucas Beltran', 'Moise Kean', 'Andrea Belotti', 'Rolando Mandragora', 'Dodo', 'Pietro Terracciano'],
  'Club Brugge': ['Hans Vanaken', 'Andreas Skov Olsen', 'Ferran Jutgla', 'Simon Mignolet', 'Brandon Mechele', 'Hugo Vetlesen', 'Michal Skoras'],
  'Real Betis': ['Isco', 'Pablo Fornals', 'Chimy Avila', 'Giovani Lo Celso', 'Marc Roca', 'Hector Bellerin', 'Rui Silva'],
  'Juventus FC': ['Dusan Vlahovic', 'Gleison Bremer', 'Manuel Locatelli', 'Kenan Yildiz', 'Teun Koopmeiners', 'Andrea Cambiaso', 'Weston McKennie', 'Danilo'],
  'PSV Eindhoven': ['Luuk de Jong', 'Joey Veerman', 'Johan Bakayoko', 'Sergino Dest', 'Jerdy Schouten', 'Walter Benitez', 'Noa Lang', 'Olivier Boscagli'],
  'Feyenoord Rotterdam': ['Santiago Gimenez', 'David Hancko', 'Quinten Timber', 'Igor Paixao', 'Justin Bijlow', 'Luka Ivanusec', 'Ramiz Zerrouki'],
  'West Ham United': ['Jarrod Bowen', 'Lucas Paqueta', 'Mohammed Kudus', 'Edson Alvarez', 'Max Kilman', 'Tomas Soucek', 'Emerson Palmieri', 'Alphonse Areola'],
  'Lille OSC': ['Jonathan David', 'Benjamin Andre', 'Edon Zhegrova', 'Lucas Chevalier', 'Angel Gomes', 'Bafode Diakite', 'Remy Cabella'],
  'AC Milan': ['Rafael Leao', 'Theo Hernandez', 'Christian Pulisic', 'Mike Maignan', 'Fikayo Tomori', 'Alvaro Morata', 'Ismael Bennacer', 'Ruben Loftus-Cheek'],
  'Olympique Lyon': ['Alexandre Lacazette', 'Corentin Tolisso', 'Maxence Caqueret', 'Rayan Cherki', 'Nicolas Tagliafico', 'Georges Mikautadze', 'Nemanja Matic', 'Anthony Lopes'],
  'FK Bodø/Glimt': ['Patrick Berg', 'Jens Petter Hauge', 'Ulrik Saltnes', 'Fredrik Bjørkan', 'Runar Espejord', 'Nikita Haikin'],
  'SC Braga': ['Ricardo Horta', 'Simon Banza', 'Rodrigo Zalazar', 'Bruma', 'Mutassim Al Musrati', 'Matheus', 'Victor Gomez'],
  'SSC Napoli': ['Khvicha Kvaratskhelia', 'Giovanni Di Lorenzo', 'Stanislav Lobotka', 'Alex Meret', 'Romelu Lukaku', 'Scott McTominay', 'Frank Anguissa', 'Mathias Olivera'],
  'AZ Alkmaar': ['Jordy Clasie', 'Sven Mijnans', 'Bruno Martins Indi', 'Riechedly Bazoer', 'Sam Beukema', 'Mathew Ryan'],
  'Olympiakos Pireus': ['Ayoub El Kaabi', 'Daniel Podence', 'Kostas Fortounis', 'Rodinei', 'David Carmo', 'Stevan Jovetic', 'Chiquinho', 'Alexandros Paschalakis'],
  'RB Lipsk': ['Lois Openda', 'Benjamin Sesko', 'Xavi Simons', 'Willi Orban', 'Peter Gulacsi', 'Castello Lukeba', 'Amadou Haidara', 'Benjamin Henrichs'],
  'Rangers FC': ['James Tavernier', 'Cyriel Dessers', 'Todd Cantwell', 'John Lundstram', 'Jack Butland', 'Connor Goldson', 'Rabbi Matondo'],
  'Villarreal CF': ['Gerard Moreno', 'Dani Parejo', 'Alex Baena', 'Thierno Barry', 'Eric Bailly', 'Yeremy Pino', 'Santi Comesana'],
  'Lazio Rzym': ['Mattia Zaccagni', 'Ivan Provedel', 'Matteo Guendouzi', 'Taty Castellanos', 'Alessio Romagnoli', 'Danilo Cataldi', 'Manuel Lazzari'],
  'Ajax Amsterdam': ['Brian Brobbey', 'Kenneth Taylor', 'Jordan Henderson', 'Chuba Akpom', 'Jorrel Hato', 'Steven Berghuis', 'Remko Pasveer', 'Devyne Rensch'],
  'Fenerbahce SK': ['Edin Dzeko', 'Dusan Tadic', 'Sebastian Szymański', 'Fred', 'Dominik Livakovic', 'Allan Saint-Maximin', 'Cengiz Ünder', 'Çağlar Söyüncü'],
  'Real Sociedad': ['Mikel Oyarzabal', 'Martin Zubimendi', 'Takefusa Kubo', 'Alex Remiro', 'Robin Le Normand', 'Hamari Traore', 'Brais Mendez'],
  'SC Freiburg': ['Vincenzo Grifo', 'Lucas Höler', 'Michael Gregoritsch', 'Matthias Ginter', 'Ritsu Doan', 'Christian Günter', 'Noah Atubolu'],
  'Szachtar Donieck': ['Georgiy Sudakov', 'Danylo Sikan', 'Artem Bondarenko', 'Taras Stepanenko', 'Mykola Matvienko', 'Lassina Traore', 'Dmytro Riznyk'],
  'AS Monaco': ['Aleksandr Golovin', 'Folarin Balogun', 'Denis Zakaria', 'Takumi Minamino', 'Breel Embolo', 'Caio Henrique', 'Thilo Kehrer'],
  'FC Kopenhaga': ['Viktor Claesson', 'Mohamed Elyounoussi', 'Rasmus Falk', 'Roony Bardghji', 'Elias Achouri', 'Kevin Diks', 'Denis Vavro'],
  'Olympique Marsylia': ['Amine Harit', 'Mason Greenwood', 'Valentin Rongier', 'Leonardo Balerdi', 'Geoffrey Kondogbia', 'Luis Henrique', 'Geronimo Rulli'],
  'Galatasaray SK': ['Mauro Icardi', 'Dries Mertens', 'Lucas Torreira', 'Victor Osimhen', 'Michy Batshuayi', 'Baris Alper Yilmaz', 'Fernando Muslera', 'Davinson Sanchez'],
  'Ferencváros': ['Barnabas Varga', 'Kristoffer Zachariassen', 'Adama Traore', 'Denes Dibusz', 'Eldar Civic', 'Mohamed Ali Ben Romdhane'],
  'Viktoria Pilzno': ['Pavel Sulc', 'Lukas Kalvach', 'Jan Kopic', 'Sampson Dweh', 'Marian Tvrdoň', 'Matej Vydra'],
  'FC Midtjylland': ['Cho Gue-sung', 'Ola Brynhildsen', 'Aral Simsir', 'Paulinho', 'Jonas Lössl', 'Kristoffer Olsson'],
  'PAOK Saloniki': ['Andrija Zivkovic', 'Kiril Despodov', 'Thomas Murg', 'Giannis Konstantelias', 'Dominik Kotarski', 'Taison', 'Abdul Rahman Baba'],
  'Union Saint-Gilloise': ['Anthony Moris', 'Christian Burgess', 'Koki Machida', 'Charles Vanhoutte', 'Dennis Eckert Ayensa'],
  'Crvena Zvezda': ['Sherif Ndiaye', 'Mirko Ivanic', 'Aleksandar Dragovic', 'Guelor Kanga', 'Omri Glazer', 'Milan Rodic'],
  'Dinamo Zagrzeb': ['Bruno Petkovic', 'Martin Baturina', 'Arijan Ademi', 'Stefan Ristovski', 'Danijel Zagorac', 'Josip Misic'],
  'RB Salzburg': ['Karim Konate', 'Oscar Gloukh', 'Amar Dedic', 'Maurits Kjaergaard', 'Lucas Gourna-Douath', 'Alexander Schlager'],
  'Celtic FC': ['Kyogo Furuhashi', 'Daizen Maeda', 'Callum McGregor', 'Reo Hatate', 'Nicolas Kühn', 'Alistair Johnston', 'Cameron Carter-Vickers', 'Kasper Schmeichel'],
  'Slavia Praga': ['Mojmir Chytil', 'Ivan Schranz', 'Petr Sevcik', 'Igoh Ogbu', 'Lukas Provod', 'Tomas Holes', 'Jindrich Stanek'],
  'Karabach FK': ['Juninho', 'Yassine Benzia', 'Abdellah Zoubir', 'Marko Vesovic', 'Julio Romao', 'Bahlul Mustafazada'],
  'KAA Gent': ['Sven Kums', 'Davy Roef', 'Tsuyoshi Watanabe', 'Archie Brown', 'Omri Gandelman', 'Hugo Gambor'],
  'Sevilla FC': ['Lucas Ocampos', 'Jesus Navas', 'Loic Bade', 'Dodi Lukebakio', 'Suso', 'Nemanja Gudelj', 'Marcao', 'Orjan Nyland'],
  'Athletic Bilbao': ['Inaki Williams', 'Nico Williams', 'Oihan Sancet', 'Gorka Guruzeta', 'Unai Simon', 'Alex Berenguer', 'Dani Vivian', 'Yuri Berchiche'],
  'Sparta Praga': ['Jan Kuchta', 'Lukas Haraslin', 'Veljko Birmancevic', 'Kaan Kairinen', 'Peter Vindahl', 'Filip Panak'],
  'Slovan Bratysława': ['Juraj Kucka', 'Vladimir Weiss', 'Tigran Barseghyan', 'David Strelec', 'Guram Kashia', 'Milan Borjan'],
  'Stade Rennais': ['Benjamin Bourigeaud', 'Arnaud Kalimuendo', 'Amine Gouiri', 'Steve Mandanda', 'Ludovic Blas', 'Adrien Truffert'],
  'FC Basel': ['Leon Avdullahu', 'Marwin Hitz', 'Dominik Schmid', 'Arnau Comas', 'Fabian Frei', 'Taulant Xhaka'],
  'Legia Warszawa': ['Tomas Pekhart', 'Marc Gual', 'Radovan Pankov', 'Juergen Elitim', 'Ryoya Morishita', 'Bartosz Kapustka', 'Rafal Augustyniak', 'Artur Jedrzejczyk', 'Steve Kapuadi', 'Patryk Kun'],
  'Maccabi Tel Awiw': ['Eran Zahavi', 'Dor Peretz', 'Gabi Kanichowsky', 'Roy Mishpati', 'Sheran Yeini', 'Dan Biton'],
  'Djurgården': ['Marcus Danielson', 'Tobias Gulliksen', 'Samuel Leach Holm', 'Albin Ekdal', 'Rasmus Schüller', 'Jacob Widell Zetterström'],
  'Bologna FC': ['Lewis Ferguson', 'Riccardo Orsolini', 'Remo Freuler', 'Stefan Posch', 'Sam Beukema', 'Michel Aebischer', 'Lukasz Skorupski'],
  'Anderlecht Bruksela': ['Kasper Dolberg', 'Thorgan Hazard', 'Jan Vertonghen', 'Anders Dreyer', 'Ludwig Augustinsson', 'Mario Stroeykens', 'Colin Coosemans'],
  'Newcastle United': ['Alexander Isak', 'Bruno Guimaraes', 'Anthony Gordon', 'Kieran Trippier', 'Sven Botman', 'Nick Pope', 'Sandro Tonali', 'Joelinton'],
  'Rapid Wiedeń': ['Guido Burgstaller', 'Nenad Cvetkovic', 'Lukas Grgic', 'Niklas Hedl', 'Jonas Auer'],
  'BSC Young Boys': ['Meschack Elia', 'Cedric Itten', 'Joel Monteiro', 'Filip Ugrinic', 'Sandro Lauper', 'David von Ballmoos', 'Loris Benito'],
  'Panathinaikos AO': ['Fotis Ioannidis', 'Daniel Mancini', 'Willian Arao', 'Tin Jedvaj', 'Facundo Pellistri', 'Bart Schenkeveld', 'Yuri Lodygin'],
  'KRC Genk': ['Tolu Arokodare', 'Bryan Heynen', 'Patrik Hrosovsky', 'Carlos Cuesta', 'Hendrik Van Crombrugge'],
  'Łudogorec Razgrad': ['Bernard Tekpetey', 'Rwan Seco', 'Jakub Piotrowski', 'Caio Vidal', 'Olivier Verdon', 'Anton Nedyalkov', 'Sergio Padt'],
  'Sturm Graz': ['Otar Kiteishvili', 'Mika Biereth', 'William Bøving', 'Jon Gorenc Stankovic', 'Dimitry Lavalée', 'Gregory Wüthrich', 'Kjell Scherpen'],
  'VfB Stuttgart': ['Deniz Undav', 'Chris Führich', 'Enzo Millot', 'Alexander Nübel', 'Angelo Stiller', 'Maximilian Mittelstädt', 'Atakan Karazor', 'Jeff Chabot'],
  'Lech Poznań': ['Mikael Ishak', 'Joel Pereira', 'Ali Gholizadeh', 'Afonso Sousa', 'Radoslaw Murawski', 'Bartosz Mrozek', 'Antonio Milic', 'Michal Gurgul', 'Dino Hotic', 'Elias Andersson'],
  'FCSB': ['Darius Olaru', 'Adrian Sut', 'Vlad Chiriches', 'Stefan Tarnovanu', 'Mihai Lixandru', 'David Miculescu'],
  'Pafos': ['Jairo', 'Muamer Tankovic', 'David Goldar', 'Ivica Ivusic', 'Vlad Dragomir', 'Pêpê Rodrigues'],
  'AEK Ateny': ['Levi Garcia', 'Steven Zuber', 'Orbelin Pineda', 'Domagoj Vida', 'Erik Lamela', 'Damian Szymański', 'Harold Moukoudi'],
  'Nottingham Forest': ['Morgan Gibbs-White', 'Taiwo Awoniyi', 'Anthony Elanga', 'Murillo', 'Callum Hudson-Odoi', 'Chris Wood', 'Ryan Yates', 'Matz Sels'],
  'Crystal Palace': ['Eberechi Eze', 'Jean-Philippe Mateta', 'Marc Guehi', 'Adam Wharton', 'Tyrick Mitchell', 'Daniel Muñoz', 'Dean Henderson'],
  'Brighton & Hove Albion': ['Kaoru Mitoma', 'Joao Pedro', 'Lewis Dunk', 'Evan Ferguson', 'Danny Welbeck', 'Yankuba Minteh', 'Billy Gilmour', 'Bart Verbruggen'],
  'Leicester City': ['Jamie Vardy', 'Stephy Mavididi', 'Harry Winks', 'Jannik Vestergaard', 'Mads Hermansen', 'Wout Faes', 'Ricardo Pereira'],
  'NK Celje': ['Aljosa Matko', 'Zan Karnicnik', 'Luka Bobicanec', 'Denis Popovic', 'Damjan Vuklisevic', 'Matjaz Rozman'],
  'Union Berlin': ['Kevin Volland', 'Danilho Doekhi', 'Frederik Rønnow', 'Lucas Tousart', 'Christopher Trimmel', 'Diogo Leite', 'Rani Khedira'],
  'Raków Częstochowa': ['Ivi Lopez', 'Vladyslav Kochergin', 'Fran Tudor', 'Jean Carlos', 'Gustav Berggren', 'Kacper Trelowski', 'Matej Rodin', 'Kamil Pestka', 'Patryk Makuch', 'Jonatan Braut Brunes'],
  'Rayo Vallecano': ['Isi Palazon', 'Alvaro Garcia', 'Oscar Trejo', 'James Rodriguez', 'Florian Lejeune', 'Alfonso Espino'],
  'Jagiellonia Białystok': ['Jesus Imaz', 'Nene', 'Taras Romanczuk', 'Afimico Pululu', 'Kristoffer Hansen', 'Adrian Dieguez', 'Mateusz Skrzypczak', 'Slawomir Abramowicz', 'Aurelien Nguiamba', 'Dusan Stojinovic'],
  'Partizan Belgrad': ['Bibars Natcho', 'Ghayas Zahid', 'Svetozar Markovic', 'Aldo Kalulu', 'Aleksandar Jovanovic'],
  'Molde FK': ['Magnus Wolff Eikrem', 'Emil Breivik', 'Kristian Eriksen', 'Veton Berisha', 'Martin Linnes', 'Albert Posiadala'],
  'RC Strasbourg': ['Emanuel Emegha', 'Habib Diarra', 'Dilane Bakwa', 'Thomas Delaine', 'Matz Sels', 'Alaa Bellaarouch'],
  'Omonia Nikozja': ['Willy Semedo', 'Andronikos Kakoullis', 'Roman Bezus', 'Moreto Cassama', 'Fabiano', 'Charalampis Charalampous'],
  'FC Lugano': ['Renato Steffen', 'Mattia Bottani', 'Jonathan Sabbatini', 'Amir Saipi', 'Milot Hajrizi'],
  'LASK Linz': ['Robert Zulj', 'Marin Ljubicic', 'Sascha Horvath', 'Philipp Ziereis', 'Tobias Lawal', 'Valon Berisha'],
  'AEK Larnaka': ['Fran Sol', 'Pere Pons', 'Angel Garcia', 'Kenan Piric', 'Hrvoje Milicevic'],
  'Pogoń Szczecin': ['Kamil Grosicki', 'Efthymis Koulouris', 'Alexander Gorgon', 'Valentin Cojocaru', 'Linus Wahlqvist', 'Vahan Bichakhchyan', 'Adrian Przyborek', 'Mariusz Malec', 'Fredrik Ulvestad', 'Rafal Kurzawa']
};

function getRandomPlayer(teamName) {
  const players = PLAYERS_DB[teamName];
  if (players && players.length > 0) {
    const idx = Math.floor(Math.random() * players.length);
    return players[idx];
  }
  // Fallback player name using teamName
  return `${teamName} Zawodnik`;
}

module.exports = {
  PLAYERS_DB,
  getRandomPlayer
};
